version: '3.9'

services:
  db:
    image: postgres:17
    container_name: postgres-db
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - alg_network
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    ports:
      - "${API_PORT}:8000"
    env_file:
      - ../.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - alg_network
    command: uvicorn --factory app.api.main:create_app --host 0.0.0.0 --port 8000
    volumes:
      - ../app:/app
      - ../migrations:/app/migrations

  frontend:
    build:
      context: ..
      dockerfile: Dockerfile
      target: frontend
    container_name: frontend-app
    ports:
      - "${FRONTEND_PORT}:3000"
    volumes:
      - ../frontend:/app/frontend
      - /app/frontend/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - alg_network
    command: npm run dev

networks:
  alg_network:
    driver: bridge

volumes:
  pgdata:
