version: '3.9'

services:
  db:
    image: postgres:17
    container_name: postgres-db
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRE_HOST: db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - alg_network
    volumes:
      - pgdata:/var/lib/postgres/data

  main-app:
    build:
      context: ..
      dockerfile: Dockerfile 
    container_name: main-app
    ports:
      - "${API_PORT}:8000"
    command: "uvicorn --factory api.main:create_app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - ../.env
    volumes:
      - ../app/:/app/
    depends_on:
      - db 
    networks:
      - alg_network

  alembic:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: alembic_migration
    depends_on:
      - db
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
    networks:
      alg_network:
    command: alembic upgrade head

networks:
  alg_network:
    driver: bridge

volumes:
  pgdata:
